version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: remote-config-db
    environment:
      POSTGRES_DB: remote_config
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js 애플리케이션
  app:
    build: .
    container_name: remote-config-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: remote_config
      DB_USER: postgres
      DB_PASSWORD: password
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run init-db && npm start"

volumes:
  postgres_data: 